services:
  y-webrtc-signaling:
    build: .
    image: yjs/y-webrtc:latest
    ports:
      - 127.0.0.1:4444:4444
    environment:
      - PORT=4444
      - NODE_ENV=production
      - CLOUDFLARE_TUNNEL=true
      - HOST_DOMAIN=${HOST_DOMAIN}
      - API_ORIGINS=${API_ORIGINS}
    networks:
      - y-webrtc
    env_file:
      - .env

networks:
  y-webrtc:
    driver: bridge